# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('chain_names', models.TextField()),
                ('has_childred', models.BooleanField()),
            ],
            options={
                'ordering': ['parent_id', 'id'],
            },
        ),
    ]
